version: 2

project_name: delegation-layer

builds:
  - id: delegate
    main: ./cmd/delegate
    binary: delegate
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X main.version={{.Version}}
  - id: delegate-run
    main: ./cmd/delegate-run
    binary: delegate-run
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X main.version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ title .Os }}_{{ .Arch }}"
    files:
      - src: .release/pueue/{{ .Os }}/{{ .Arch }}/pueue
        dst: pueue
      - src: .release/pueue/{{ .Os }}/{{ .Arch }}/pueued
        dst: pueued

checksum:
  name_template: "checksums.txt"

release:
  draft: true
  mode: keep-existing
